# 02: Modelling: Baselines to SARIMAX to LightGBM

Narrative companion to `src/models/` and `src/evaluate.py`.

**Task definition.** Day-ahead forecasting: at the end of day *D* predict all 24
hours of day *D+1*. This mirrors how load forecasts feed the day-ahead power
market. Every design decision below follows from that origin/horizon choice.

**Anti-leakage rule.** A feature is admissible only if it is known at the
origin. All lag/rolling features are therefore shifted ≥ 24 h, and the tree
model becomes a *direct* day-ahead forecaster, no recursive feedback of its
own predictions.

> Run the pipeline first: `python -m src.data_ingestion && python -m src.features`.

In [1]:
import sys
from pathlib import Path
sys.path.append(str(Path.cwd().parent))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from src.config import TARGET, TEST_WEEKS
from src.data_ingestion import load_processed
from src.features import FEATURES, load_features

df = load_processed()
feats = load_features()
print(f'{feats.shape[0]:,} rows, {len(FEATURES)} features')
feats.head(3)

34,873 rows, 17 features

,total load actual,hour,weekday,month,is_weekend,is_holiday,hour_sin,hour_cos,doy_sin,doy_cos,lag_24h,lag_48h,lag_168h,roll_mean_24h,roll_mean_168h,roll_std_24h,temp,temp_sq
time,,,,,,,,,,,,,,,,,,
2015-01-08 22:00:00+00:00,26436.0,23,3,1,0,0,-0.258819,0.965926,0.137185,0.990545,30477.0,27421.0,26798.0,32105.000000,26569.744048,3750.439313,4.1384,17.126355
2015-01-08 23:00:00+00:00,27485.0,0,4,1,0,0,0.000000,1.000000,0.154204,0.988039,26788.0,30518.0,27070.0,31949.583333,26578.095238,3893.615185,3.9574,15.661015
2015-01-09 00:00:00+00:00,25750.0,1,4,1,0,0,0.258819,0.965926,0.154204,0.988039,25146.0,28484.0,24935.0,31810.500000,26582.642857,4078.041516,3.5988,12.951361

## 1. Baselines: the bar to clear

* **naive-24h**: tomorrow = today (per hour).
* **seasonal naive-168h**: tomorrow = same day last week.

Load is so strongly autocorrelated that these are hard to beat; any model that
cannot outperform them has no business value.

In [2]:
from src.models.baselines import naive_24h, seasonal_naive_168h

y = df[TARGET]
test_idx = y.index[-28 * 24:]
for name, fn in [('naive-24h', naive_24h), ('seasonal-naive-168h', seasonal_naive_168h)]:
    p = fn(y, test_idx)
    m = p.notna()
    print(f'{name:>20s}  MAPE(last 28d) = '
          f'{np.mean(np.abs((y[test_idx][m]-p[m])/y[test_idx][m]))*100:.2f}%')

           naive-24h  MAPE(last 28d) = 9.29%
 seasonal-naive-168h  MAPE(last 28d) = 11.85%

## 2. SARIMAX on daily means with temperature exog

Hourly load has three stacked seasonalities, which a single SARIMA cannot
represent well, so the classical model works at the **daily** level:
weekly seasonal order (s = 7) plus exogenous `temp` and centred `temp²`
(the U-shape). Order is selected by AIC over a small grid, the full ranked
table is persisted to `reports/sarimax_order_selection.csv` for the write-up.

For comparability with hourly models, its daily forecast is disaggregated to
hourly using the train-period hour-of-week profile.

In [3]:
from src.models import sarimax_model as sm

daily = sm.make_daily(df)
train = daily.iloc[:-TEST_WEEKS * 7]   # never touch the backtest window
# reuses reports/sarimax_order.json, the order the backtest in src/evaluate.py uses
order, seasonal = sm.load_or_select_order(train[TARGET], sm.exog_matrix(train))
print('AIC-selected order:', order, 'x', seasonal)
res = sm.fit(train[TARGET], sm.exog_matrix(train), order, seasonal)
res.summary()

AIC-selected order: (1, 1, 2) x (0, 1, 1, 7)

<class 'statsmodels.iolib.summary.Summary'>
"""
                                      SARIMAX Results
===========================================================================================
Dep. Variable:                   total load actual   No. Observations:                 1378
Model:             SARIMAX(1, 1, 2)x(0, 1, [1], 7)   Log Likelihood              -12472.969
Date:                             Tue, 27 Oct 2026   AIC                          24959.937
Time:                                     13:01:46   BIC                          24996.444
Sample:                                 12-31-2014   HQIC                         24973.604
                                      - 10-08-2018
Covariance Type:                               opg
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
temp          70.8682     25.967      2.729      0.006      19.973     121.763
temp_sq       21.1870      2.015     10.516      0.000      17.238      25.136
ar.L1          0.2633      0.050      5.222      0.000       0.164       0.362
ma.L1         -0.9256      0.054    -17.200      0.000      -1.031      -0.820
ma.L2         -0.1040      0.055     -1.876      0.061      -0.213       0.005
ma.S.L7       -0.9907      0.010   -101.650      0.000      -1.010      -0.972
sigma2      4.757e+06   1.46e+05     32.514      0.000    4.47e+06    5.04e+06
===================================================================================
Ljung-Box (L1) (Q):                   0.00   Jarque-Bera (JB):               242.46
Prob(Q):                              0.99   Prob(JB):                         0.00
Heteroskedasticity (H):               0.79   Skew:                            -0.37
Prob(H) (two-sided):                  0.01   Kurtosis:                         4.93
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
"""

In [4]:
pd.read_csv('../reports/sarimax_order_selection.csv').head(8)

       order seasonal_order          aic
0  (1, 1, 2)   (0, 1, 1, 7)  6403.501376
1  (2, 1, 2)   (0, 1, 1, 7)  6404.967386
2  (1, 1, 2)   (1, 1, 1, 7)  6405.658205
3  (2, 1, 2)   (1, 1, 1, 7)  6414.751905
4  (0, 1, 2)   (1, 1, 1, 7)  6414.947233
5  (0, 1, 2)   (0, 1, 1, 7)  6417.595978
6  (2, 1, 1)   (0, 1, 1, 7)  6430.699474
7  (2, 1, 1)   (1, 1, 1, 7)  6432.801789

## 3. LightGBM: the main model

Gradient-boosted trees on the full feature set: calendar (incl. Spanish
holidays), lags (24/48/168 h), day-ahead-safe rolling statistics, and the
temperature terms. Trees capture the hour×weekday×temperature interactions
that the linear models cannot.

In [5]:
from src.models.lgbm_model import train_point

cutoff = feats.index.max() - pd.Timedelta(weeks=TEST_WEEKS)
train_f = feats[feats.index <= cutoff]
model = train_point(train_f[FEATURES], train_f[TARGET])

imp = pd.Series(model.feature_importances_, index=FEATURES).sort_values()
imp.plot.barh(figsize=(8, 7), title='LightGBM feature importance (splits)');

## 4. Prediction intervals: quantile LightGBM

Procurement decisions need *ranges*, not just points. Three additional
LightGBM models trained with pinball loss at α = 0.10 / 0.50 / 0.90 provide a
day-ahead P10-P90 band (sorted post-hoc to guarantee monotonicity).

In [6]:
from src.models.lgbm_model import train_quantiles, predict_quantiles

q_models = train_quantiles(train_f[FEATURES], train_f[TARGET])
week = feats[(feats.index > cutoff) & (feats.index <= cutoff + pd.Timedelta(days=7))]
band = predict_quantiles(q_models, week[FEATURES])

plt.figure(figsize=(13, 5))
plt.fill_between(band.index, band['p10'], band['p90'], alpha=0.25, label='P10-P90')
plt.plot(week.index, week[TARGET], color='black', lw=1.3, label='Actual')
plt.plot(band.index, band['p50'], color='tab:blue', lw=1.3, label='P50')
plt.legend(); plt.title('Quantile band on the first unseen week');

## 5. Honest evaluation: rolling-origin backtest + Diebold-Mariano

A single train/test split can flatter or punish a model by luck. The proper
protocol (in `src/evaluate.py`) rolls the forecast origin day by day across the
final 12 weeks (~2,000 hourly predictions), refitting LightGBM weekly and
updating SARIMAX's state daily.

Because forecast errors at a 24 h horizon are autocorrelated, "model A's MAPE
is lower" is not enough, the **Diebold-Mariano test** (squared-error loss,
equal-weight variance from the first 23 autocovariances,
Harvey-Leybourne-Newbold small-sample correction) checks whether the accuracy
gap between the top two models is statistically significant. Results land in
`reports/results.md` and the README; `src/sensitivity.py` repeats the test under
other loss functions and by day.

In [7]:
# Full backtest (a few minutes):
#   python -m src.evaluate
from src.config import REPORTS
res_file = REPORTS / 'results.md'
if res_file.exists():
    from IPython.display import Markdown
    display(Markdown(res_file.read_text()))
else:
    print('Run `python -m src.evaluate` to generate backtest results.')

## Backtest results - rolling-origin day-ahead, final 12 weeks (2016 hourly forecasts)

| model               |   MAPE_% |   RMSE_MW |   MAE_MW |
|:--------------------|---------:|----------:|---------:|
| LightGBM            |     4.68 |   2219.11 |  1352.76 |
| SARIMAX(daily)+temp |     6.06 |   2483.55 |  1712.31 |
| Naive-24h           |     7.9  |   3271.59 |  2249.02 |
| SeasonalNaive-168h  |     9.01 |   3772.58 |  2555.4  |

**Diebold-Mariano** (LightGBM vs SARIMAX(daily)+temp, squared-error loss, h=24, HLN-adjusted): statistic = **-1.46**, p-value = **0.14**

**LightGBM P10-P90 interval:** empirical coverage 68.5% (nominal 80%)

## Conclusions

* Lag structure carries most of the signal, but holidays decide the hardest
  days: the five worst days carry 43% of each model's squared error.
* SARIMAX is a solid, interpretable statistical reference once temperature
  enters as an exogenous quadratic, but one daily value spread by a fixed
  profile cannot react to hour-level dynamics.
* LightGBM with leakage-safe features has the lowest error on every metric and
  at every hour. The squared-error DM test does not reach significance on this
  12-week window (p = 0.14) because a few holiday days dominate; absolute-error
  and by-day checks (`reports/dm_sensitivity.json`) favour LightGBM.
* Quantile models add the P10-P90 band that procurement actually consumes.

Next: `python -m src.forecast` for the operational next-24h forecast, and
`streamlit run app.py` for the interactive dashboard.